# Generated by Django 4.2.14 on 2026-05-23 10:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=50, unique=True, verbose_name="用户名"),
                ),
                ("password", models.CharField(max_length=255, verbose_name="密码")),
                (
                    "real_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="真实姓名"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="联系电话"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后登录时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "管理员",
                "verbose_name_plural": "管理员",
                "db_table": "admin_user",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="部门名称"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="部门编码"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "部门",
                "verbose_name_plural": "部门",
                "db_table": "department",
            },
        ),
        migrations.CreateModel(
            name="InsuranceCompany",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="投保公司名称"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="公司编码"
                    ),
                ),
                (
                    "contact",
                    models.CharField(blank=True, max_length=50, verbose_name="联系人"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="联系电话"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "投保公司",
                "verbose_name_plural": "投保公司",
                "db_table": "insurance_company",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="供应商名称"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="供应商编码"
                    ),
                ),
                (
                    "contact",
                    models.CharField(blank=True, max_length=50, verbose_name="联系人"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="联系电话"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "供应商",
                "verbose_name_plural": "供应商",
                "db_table": "supplier",
            },
        ),
        migrations.CreateModel(
            name="Premium",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="开始时间")),
                ("end_date", models.DateField(verbose_name="截止时间")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="保费总额(元)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "insurance_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="premiums",
                        to="StaffManage.insurancecompany",
                        verbose_name="投保公司",
                    ),
                ),
            ],
            options={
                "verbose_name": "保费信息",
                "verbose_name_plural": "保费信息",
                "db_table": "premium",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="姓名")),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("TYPE1", "一类"),
                            ("TYPE2", "二类"),
                            ("TYPE3", "三类"),
                        ],
                        max_length=10,
                        verbose_name="工种",
                    ),
                ),
                (
                    "premium_standard",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="保费标准(每天)"
                    ),
                ),
                (
                    "real_time_premium",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="实时保费",
                    ),
                ),
                ("hire_date", models.DateField(verbose_name="入职时间")),
                (
                    "leave_date",
                    models.DateField(blank=True, null=True, verbose_name="离职时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ON", "在职"), ("OFF", "离职")],
                        default="ON",
                        max_length=10,
                        verbose_name="在职状态",
                    ),
                ),
                (
                    "id_card",
                    models.CharField(
                        max_length=18, unique=True, verbose_name="身份证号"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="联系电话"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="StaffManage.department",
                        verbose_name="所属部门",
                    ),
                ),
                (
                    "insurance_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="StaffManage.insurancecompany",
                        verbose_name="投保公司",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="StaffManage.supplier",
                        verbose_name="供应商",
                    ),
                ),
            ],
            options={
                "verbose_name": "员工",
                "verbose_name_plural": "员工",
                "db_table": "employee",
            },
        ),
    ]
