# Generated by Django 4.2.14 on 2026-05-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("sex", models.CharField(blank=True, max_length=10)),
                ("type", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
