# Generated by Django 4.2.14 on 2026-05-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("StaffManage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "admin_user",
            },
        ),
        migrations.AlterModelTable(
            name="userinfo",
            table="user_info",
        ),
    ]
