# Generated by Django 4.2.14 on 2026-05-18 11:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StaffManage', '0002_adminuser_alter_userinfo_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('FIXED', '固定期限劳动合同'), ('OPEN', '无固定期限劳动合同'), ('PART_TIME', '非全日制用工合同'), ('OUTSOURCE', '劳务派遣合同')], max_length=20, verbose_name='合同类型')),
                ('contract_no', models.CharField(max_length=50, unique=True, verbose_name='合同编号')),
                ('start_date', models.DateField(verbose_name='合同起始日')),
                ('end_date', models.DateField(verbose_name='合同终止日')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='合同月薪')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('ACTIVE', '生效中'), ('EXPIRED', '已过期'), ('TERMINATED', '已终止')], default='ACTIVE', max_length=20, verbose_name='合同状态')),
                ('file_path', models.CharField(blank=True, max_length=255, verbose_name='合同文件路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '劳动合同',
                'verbose_name_plural': '劳动合同',
                'db_table': 'contract',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='部门名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='部门编码')),
                ('leader', models.CharField(blank=True, max_length=50, verbose_name='部门负责人')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='部门电话')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='StaffManage.department', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=200, verbose_name='毕业学校')),
                ('major', models.CharField(max_length=100, verbose_name='专业')),
                ('degree', models.CharField(choices=[('HS', '高中/中专'), ('CJ', '大专'), ('BK', '本科'), ('SS', '硕士'), ('BS', '博士')], max_length=10, verbose_name='学历')),
                ('start_date', models.DateField(verbose_name='入学日期')),
                ('end_date', models.DateField(verbose_name='毕业日期')),
                ('diploma_no', models.CharField(blank=True, max_length=50, verbose_name='毕业证号')),
            ],
            options={
                'verbose_name': '学历信息',
                'verbose_name_plural': '学历信息',
                'db_table': 'education',
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='联系人姓名')),
                ('relation', models.CharField(choices=[('SPOUSE', '配偶'), ('CHILD', '子女'), ('PARENT', '父母'), ('SIBLING', '兄弟姐妹'), ('OTHER', '其他')], max_length=20, verbose_name='关系')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='住址')),
            ],
            options={
                'verbose_name': '紧急联系人',
                'verbose_name_plural': '紧急联系人',
                'db_table': 'emergency_contact',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_no', models.CharField(max_length=20, unique=True, verbose_name='工号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性别')),
                ('id_card', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('birth_date', models.DateField(verbose_name='出生日期')),
                ('marital_status', models.CharField(choices=[('S', '未婚'), ('M', '已婚'), ('D', '离异'), ('W', '丧偶')], default='S', max_length=1, verbose_name='婚姻状况')),
                ('blood_type', models.CharField(blank=True, choices=[('A', 'A型'), ('B', 'B型'), ('O', 'O型'), ('AB', 'AB型')], max_length=3, verbose_name='血型')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号码')),
                ('email', models.EmailField(max_length=254, verbose_name='电子邮箱')),
                ('native_place', models.CharField(blank=True, max_length=200, verbose_name='籍贯')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='现住地址')),
                ('emergency_contact', models.CharField(blank=True, max_length=50, verbose_name='紧急联系人')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, verbose_name='紧急联系电话')),
                ('status', models.CharField(choices=[('ONBOARD', '在职'), ('PROBATION', '试用期'), ('LEAVE', '离职'), ('RETIRED', '退休')], default='PROBATION', max_length=20, verbose_name='员工状态')),
                ('hire_date', models.DateField(verbose_name='入职日期')),
                ('contract_start', models.DateField(verbose_name='合同起始日期')),
                ('contract_end', models.DateField(verbose_name='合同结束日期')),
                ('social_security_no', models.CharField(blank=True, max_length=30, verbose_name='社保账号')),
                ('bank_card_no', models.CharField(blank=True, max_length=30, verbose_name='工资卡号')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='开户银行')),
                ('photo', models.ImageField(blank=True, upload_to='photos/', verbose_name='照片')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='StaffManage.department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'db_table': 'employee',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='职位名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='职位编码')),
                ('level', models.CharField(choices=[('L1', 'L1-基层员工'), ('L2', 'L2-骨干员工'), ('L3', 'L3-主管级'), ('L4', 'L4-经理级'), ('L5', 'L5-总监级'), ('L6', 'L6-副总经理级'), ('L7', 'L7-总经理级')], default='L1', max_length=10, verbose_name='职级')),
                ('remark', models.TextField(blank=True, verbose_name='职位说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='StaffManage.department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '职位',
                'verbose_name_plural': '职位',
                'db_table': 'position',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_month', models.CharField(max_length=7, verbose_name='发放月份')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='基本工资')),
                ('post_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='岗位工资')),
                ('traffic_subsidy', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='交通补贴')),
                ('communication_subsidy', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='通讯补贴')),
                ('meal_subsidy', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='餐补')),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='加班费')),
                ('performance_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='绩效奖金')),
                ('social_security', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='社保扣款')),
                ('housing_fund', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='公积金扣款')),
                ('income_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='个人所得税')),
                ('other_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='其他扣款')),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='实发工资')),
                ('pay_date', models.DateField(blank=True, null=True, verbose_name='发放日期')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='StaffManage.employee', verbose_name='员工')),
            ],
            options={
                'verbose_name': '薪资记录',
                'verbose_name_plural': '薪资记录',
                'db_table': 'salary',
                'unique_together': {('employee', 'pay_month')},
            },
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
        migrations.AlterModelOptions(
            name='adminuser',
            options={'verbose_name': '管理员', 'verbose_name_plural': '管理员'},
        ),
        migrations.AddField(
            model_name='adminuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='联系电话'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='real_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='password',
            field=models.CharField(max_length=255, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='StaffManage.position', verbose_name='职位'),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='StaffManage.employee', verbose_name='员工'),
        ),
        migrations.AddField(
            model_name='education',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='StaffManage.employee', verbose_name='员工'),
        ),
        migrations.AddField(
            model_name='contract',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='StaffManage.employee', verbose_name='员工'),
        ),
    ]
